#include "profiler.hpp"

#ifdef ENABLE_PROFILER
struct overhead_profiler profilers[NUM_OVERHEAD_TYPES];

const char* overhead_profiler_type_names[NUM_OVERHEAD_TYPES] = {
	"FASTPATH",
	"DEREF_SCOPE",
	"BARRIER_ENTER_SWAP_IN",
	"BARRIER_NOT_PRESENT_SWAP_IN",
	"BARRIER_SWAP_IN_PREP",
	"BARRIER_SWAP_IN_READ",
	"BARRIER_SWAP_IN_INIT",
	"BARRIER_MIGRATION_ENTER",
	"BARRIER_MIGRATION_PREP",
	"BARRIER_MIGRATION_MOVE",
	"BARRIER_MIGRATION_INIT",
	"PREFETCH_SWAP_IN_PREP",
	"PREFETCH_SWAP_IN_READ",
	"PREFETCH_SWAP_IN_INIT",
	"SERVER_DF_VECTOR_READ",
	"SERVER_PTR_READ",
	"REMOTE_DS_CONSTRUCT",
	"REMOTE_DS_DESTRUCT",
	"REMOTE_DS_EXPAND",
#ifdef STW_GC
	"STW_GC_LATENCY",
#endif
};
#endif